version: 2
sources:
- name: anime_quotes
  database: anime_quotes
  schema: raw_quotes
  tables:
  - name: kaijuu_8_gou
  - name: tsuki_ga_michibiku_isekai_douchuu_dai_ni_maku
  - name: phantasy_star_online_2___episode_oracle
  - name: bungou_stray_dogs_2023
  - name: v_json_info
  - name: v_tables_info
  - name: paripi_koumei
  - name: boku_no_hero_academia
  - name: watashi_no_yuri_wa_oshigoto_desu___
  - name: shiro_seijo_to_kuro_bokushi
  - name: tearmoon_teikoku_monogatari___dantoudai_kara_hajimaru_hime_no_t
  - name: yahari_ore_no_seishun_lovecome_wa_machigatte_iru_kan
  - name: yuru_camp_season_3
  - name: kimitachi_wa_dou_ikiru_ka
  - name: lv2_kara_cheat_datta_moto_yuusha_kouho_no_mattari_isekai_life
  - name: hanyou_no_yashahime___sengoku_otogizoushi
  - name: kekkon_yubiwa_monogatari
  - name: kimi_to_boku_no_saigo_no_senjou_arui_wa_sekai_ga_hajimaru_seise
  - name: arslan_senki
  - name: jojo_no_kimyou_na_bouken___stone_ocean_part_3
  - name: kimetsu_no_yaiba___katanakaji_no_sato_hen
  - name: mushoku_tensei_ii___isekai_ittara_honki_dasu_2024
  - name: wind_breaker
  - name: gekijouban_hagane_no_renkinjutsushi___shambala_o_yuku_mono
  - name: keiken_zumi_na_kimi_to_keiken_zero_na_ore_ga_otsukiai_suru_hana
  - name: haikyuu_______to_the_top
  - name: hokuto_no_ken
  - name: isekai_shokudou_2
  - name: kami_no_tou
  - name: kaii_to_otome_to_kamikakushi
  - name: kono_subarashii_sekai_ni_shukufuku_o____3
  - name: kono_subarashii_sekai_ni_shukufuku_o____kurenai_densetsu
  - name: helck
  - name: boku_no_hero_academia_2018
  - name: boku_no_kokoro_no_yabai_yatsu_2024
  - name: oshi_no_ko
  - name: jaku_chara_tomozakikun
  - name: jaku_chara_tomozakikun_2nd_stage
  - name: saijaku_tamer_wa_gomi_hiroi_no_tabi_o_hajimemashita
  - name: kuroshitsuji___kishuku_gakkou_hen
  - name: lycoris_recoil
  - name: arslan_senki___fuujin_ranbu
  - name: hoshikuzu_telepath
  - name: sengoku_youko
  - name: blue_archive_the_animation
  - name: gate___jieitai_kanochi_nite_kaku_tatakaeri
  - name: hataraku_saibou
  - name: ginga_eiyuu_densetsu___die_neue_these
  - name: date_a_live_v
  - name: json_reference
  - name: sentai_dai_shikkaku
  - name: hataraku_saibou_black
  - name: yuuki_bakuhatsu_bang_bravern
  - name: senki_zesshou_symphogear_axz
  - name: _30sai_made_doutei_da_to_mahou_tsukai_ni_nareru_rashii
  - name: natsume_yuujinchou_go
  - name: the_god_of_high_school
  - name: ling_qi___huangquan_zhi_qi
  - name: nier__automata_ver11a
  - name: jigokuraku
  - name: ryza_no_atelier___tokoyami_no_joou_to_himitsu_no_kakurega
  - name: sewayaki_kitsune_no_senkosan
  - name: shingeki_no_bahamut___virgin_soul
  - name: spy_kyoushitsu
  - name: gekijouban_one_piece___stampede
  - name: infinite_dendrogram
  - name: kimetsu_no_yaiba___hashira_geiko_hen
  - name: spy_kyoushitsu_2023
  - name: kawaii_dake_ja_nai_shikimorisan
  - name: shinigami_bocchan_to_kuro_maid_2024
  - name: tokyo_godfathers
  - name: shokugeki_no_souma_oad
  - name: vampire_dormitory
  - name: sokushi_cheat_ga_saikyou_sugite_isekai_no_yatsura_ga_marude_ait
  - name: sousou_no_frieren
  - name: inuyasha_kanketsuhen
  - name: gekijouban_sword_art_online___progressive__hoshinaki_yoru_no_ar
  - name: mushoku_tensei_ii___isekai_ittara_honki_dasu
  - name: bishoujo_senshi_sailor_moon_crystal_season_iii
  - name: _16bit_sensation___another_layer
  - name: v_tables_match
  - name: beyblade_burst
  - name: dr_stone
  - name: eiga_yuru_camp
  - name: hametsu_no_oukoku
  - name: kageki_shoujo______
  - name: saikyou_onmyouji_no_isekai_tenseiki
  - name: azumanga_daiou_the_animation
  - name: kono_oto_tomare____2019
  - name: ballroom_e_youkoso
  - name: bproject___kodou_ambitious
  - name: classicaloid
  - name: darwins_game
  - name: ijiranaide_nagatorosan_2nd_attack
  - name: megumi_no_daigo___kyuukoku_no_orange
  - name: kuzu_no_honkai
  - name: kyuujitsu_no_warumonosan
  - name: princess_principal
  - name: saikyou_tank_no_meikyuu_kouryaku___tairyoku_9999_no_rare_skill_
  - name: shinobi_no_ittoki
  - name: tatoeba_last_dungeon_mae_no_mura_no_shounen_ga_joban_no_machi_d
  - name: tian_guan_cifu_di_er_ji
  - name: tenki_no_ko
  - name: bakemono_no_ko
  - name: rockmanexe
  - name: dai_501_tougou_sentou_koukuu_dan_strike_witches___road_to_berli
  - name: eiga_sasaki_to_miyano___sotsugyou_hen
  - name: kaiko_sareta_ankoku_heishi_30dai_no_slow_na_second_life
  - name: renmei_kuugun_koukuu_mahou_ongakutai_luminous_witches
  - name: dragon_ball___shen_long_no_densetsu
  - name: shinseiki_evangelion_gekijouban___air__magokoro_o_kimi_ni
  - name: akuyaku_reijou_nano_de_last_boss_o_katte_mimashita
  - name: gekijouban_sekaiichi_hatsukoi___yokozawa_takafumi_no_baai
  - name: heroman
  - name: hinamatsuri_2018
  - name: mahou_tsukai_no_yome
  - name: mahou_tsukai_no_yome___hoshi_matsu_hito
  - name: natsu_e_no_tunnel_sayonara_no_deguchi
  - name: danshi_koukousei_no_nichijou
  - name: xian_wang_de_richang_shenghuo
  - name: saihate_no_paladin___tetsusabi_no_yama_no_ou
  - name: selection_project
  - name: gekijouban_sword_art_online___progressive__kuraki_yuuyami_no_sc
  - name: wangan_midnight
  - name: bakugan_battle_brawlers
  - name: kidou_senshi_v_gundam
  - name: kubosan_wa_mob_o_yurusanai
  - name: banana_fish
  - name: mahou_tsukai_no_yome_season_2_2023
  - name: mahou_tsukai_no_yome_season_2
  - name: kikansha_no_mahou_wa_tokubetsu_desu
  - name: fairy_tail___100_years_quest
  - name: deaimon
  - name: bungou_stray_dogs_2023_tv
